package rules;

import com.ftn.carDiagnostic.dto.ReservationDTO

global java.util.List fixes;
global java.util.List appointments;
global java.util.List timeNeeded;


rule "Time for headlight fix"
	when
		ReservationDTO(getFix() == "Headlight replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for taillight fix"
	when
		ReservationDTO(getFix() == "Taillight replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end


rule "Time for Window fix"
	when
		ReservationDTO(getFix() == "Window replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end


