package rules;

import com.ftn.carDiagnostic.dto.ReservationDTO

global java.util.List fixes;
global java.util.List appointments;
global java.util.List timeNeeded;


rule "Time for headlight fix"
	when
		ReservationDTO(getFix() == "Headlight replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for taillight fix"
	when
		ReservationDTO(getFix() == "Taillight replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end


rule "Time for Window fix"
	when
		ReservationDTO(getFix() == "Window replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Window motor replacement fix"
	when
		ReservationDTO(getFix() == "Window motor replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Battery replacement fix"
	when
		ReservationDTO(getFix() == "Battery replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Electricfan replacement fix"
	when
		ReservationDTO(getFix() == "Electricfan replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for Alternator replacement fix"
	when
		ReservationDTO(getFix() == "Alternator replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for turboChargerFix fix"
	when
		ReservationDTO(getFix() == "Turbo charger replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for DPF replacement"
	when
		ReservationDTO(getFix() == "DPF replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("3");

end

rule "Time for Shockabsorber replacement"
	when
		ReservationDTO(getFix() == "Shockabsorber replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Brake disc replacement"
	when
		ReservationDTO(getFix() == "Brake disc replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for stabilizer replacement fix"
	when
		ReservationDTO(getFix() == "Stabilizer replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Brake pads replacement"
	when
		ReservationDTO(getFix() == "Brake pads replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for Engine belt replacement"
	when
		ReservationDTO(getFix() == "Engine belt replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for brake lines replacement"
	when
		ReservationDTO(getFix() == "Brake lines replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Gasket replacement"
	when
		ReservationDTO(getFix() == "Gasket replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for Dualmass flywheel replacement"
	when
		ReservationDTO(getFix() == "Dualmass flywheel replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("4");

end

rule "Time for Tyre replacement"
	when
		ReservationDTO(getFix() == "Tyre replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Oil replacement"
	when
		ReservationDTO(getFix() == "Oil replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Coolant replacement"
	when
		ReservationDTO(getFix() == "Coolant replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for Transmission fluid replacement"
	when
		ReservationDTO(getFix() == "Transmission fluid replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Freon gas replacement"
	when
		ReservationDTO(getFix() == "Freon gas replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Fuel pump replacement"
	when
		ReservationDTO(getFix() == "Fuel pump replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("2");

end

rule "Time for Fuel filter replacement"
	when
		ReservationDTO(getFix() == "Fuel filter replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for Nozlle replacement"
	when
		ReservationDTO(getFix() == "Nozzle replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end

rule "Time for sparkplug replacement"
	when
		ReservationDTO(getFix() == "Sparkplug replacement");
	then
		timeNeeded.clear();
		timeNeeded.add("1");

end



