package rules;

import com.ftn.carDiagnostic.model.fix.ElectricalPartsFix;
import com.ftn.carDiagnostic.model.fix.FluidPartsFix
import com.ftn.carDiagnostic.model.RuleReturnTest;
import com.ftn.carDiagnostic.model.fix.MechanicalPartsFix;
import com.ftn.carDiagnostic.model.fix.FuelInjectionPartsFix;
import com.ftn.carDiagnostic.model.fix.AirFlowPartsFix;

global java.util.List fixes;
global java.util.List appointments;

//DRUGA GRUPA PRAVILA, NA OSNOVU PROBLEMATICNOG DELA SE PRONALAZI POPRAVKA ZA ISTI

//ELECTRICAL PROBLEMS

rule "FAILURE ID-1 -loginFail multiple"
	when
	    $log: Log( getId() == 1 && getMessage() == 'login_fail' , $logId: id );
	    Number(intValue >= 2) from accumulate(
        $log2: Log( this != $log, id == $logId, this meets[1m] $log),count($log2))
	then
		fixes.add("ALERT! : Multiple failed login for short time! Time: " + $log.getExecutionTime() + "| Message: " + $log.getMessage() + "\n");
		delete($log);
end 

rule "Headlight fix"
    when
        $ep: ElectricalParts( isHeadlight() == true );
        $epf: ElectricalPartsFix( getHeadlightFix() != null);
       
    then
    	RuleReturnTest rr = new RuleReturnTest();
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($epf.getHeadlightFix());
    	rr.ruleReturn($epf.getHeadlightFix()); //Pozivam metodu u kojoj ce rule da vrati Fix korisniku na front 
    	

    	//System.out.println($epf.getHeadlightFix());
 end 

rule "Taillight fix"
    when
        $ep: ElectricalParts( isTailLight() == true );
        $epf: ElectricalPartsFix( getTaillightFix() != null);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($epf.getTaillightFix());
   		RuleReturnTest rr = new RuleReturnTest();
       rr.ruleReturn($epf.getTaillightFix());
end 

rule "ElectricWindows fix"
    when
        $ep: ElectricalParts( isElectricWindows() == true );
        $epf: ElectricalPartsFix( getElectricWindowsFix() != null);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($epf.getElectricWindowsFix());
    	RuleReturnTest rr = new RuleReturnTest();
      	rr.ruleReturn($epf.getElectricWindowsFix());
end 

rule "Battery fix"
    when
        $ep: ElectricalParts( isBattery() == true );
        $epf: ElectricalPartsFix( getBatteryFix() != null);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($epf.getBatteryFix());
   		RuleReturnTest rr = new RuleReturnTest();
       	rr.ruleReturn($epf.getBatteryFix());
end 

rule "Electrical fan"
    when
        $ep: ElectricalParts( isElectricFan() == true );
        $epf: ElectricalPartsFix( getElectricFanFix() != null);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($epf.getElectricFanFix());
   		RuleReturnTest rr = new RuleReturnTest();
       	rr.ruleReturn($epf.getElectricFanFix());
end 



//FLUID problems

//Verovatno samo kondenzacija, proveriti nivo rashladne tecnosti
rule "Coolant fix"
    when
        $fp: FluidParts( isCoolant() == true );
        $fpf: FluidPartsFix( getCoolantFix() != null);
    then
    	delete($fp);
    	fixes.clear();
    	fixes.addAll($fpf.getCoolantFix());
    	RuleReturnTest rr = new RuleReturnTest();
       	rr.ruleReturn($fpf.getCoolantFix());
end 

//Proveriti da li ima prijavljen problem sa uljem, jer ovo znaci da motor trosi ulje?
rule "Oil fix"
    when
        $fp: FluidParts( isOil() == true );
        $fpf: FluidPartsFix( getOilFix() != null);
    then
    	delete($fp);
    	fixes.clear();
    	fixes.addAll($fpf.getOilFix());
    	RuleReturnTest rr = new RuleReturnTest();
       	rr.ruleReturn($fpf.getOilFix());
end 


		
rule "Freon fix"
	when
		$fp: FluidParts( isFreon() == true );
		$fpf: FluidPartsFix ( getFreonFix() != null );
	then
		delete($fp);
		fixes.clear();
    	fixes.addAll($fpf.getFreonFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($fpf.getFreonFix());
end

//MECHANICAL PART FIX
rule "Brakepad fix"
	when
		$mp: MechanicalParts( isBrakePads() == true);
		$mpf: MechanicalPartsFix( getBrakePadsFix() != null);
	then
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getBrakePadsFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getBrakePadsFix());
end

rule "DPF fix"
	when
		$ap: AirFlowParts( isDieselParticulateFilter() );
		$apf: AirFlowPartsFix(getDpfFix() != null);
	then
		delete($ap);
		fixes.clear();
    	fixes.addAll($apf.getDpfFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($apf.getDpfFix());
end

rule "Shock absorber fix"
	when
		$mp: MechanicalParts( isShockAbsorber() );
		$mpf: MechanicalPartsFix( getShockAbsorberFix() != null);
	then
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getShockAbsorberFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getShockAbsorberFix());
end

rule "Brake Disc fix"
	when
		$mp: MechanicalParts( isBrakeDisc() );
		$mpf: MechanicalPartsFix( getBrakeDiscFix() != null);
	then
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getBrakeDiscFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getBrakeDiscFix());
end


rule "Stabilizer fix"
	when
		$mp: MechanicalParts( isStabilizer() );
		$mpf: MechanicalPartsFix( getStabilizerFix() != null);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getStabilizerFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getStabilizerFix());

end

rule "Engine belt fix"
	when
		$mp: MechanicalParts( isEngineBelt() );
		$mpf: MechanicalPartsFix( getEngineBeltFix() != null);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getEngineBeltFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getEngineBeltFix());

end

//FUEL INJECTION PARTS FIX
rule "Nozzle fix"
	when
		$fip: FuelInjectionParts( isNozzle() );
		$fipf: FuelInjectionPartsFix( getNozzleFix() != null);
	then
		delete($fip);
		fixes.clear();
    	fixes.addAll($fipf.getNozzleFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($fipf.getNozzleFix());
end

//AIRFLOW PARTS FIX
rule "Turbo charger fix"
	when
		$ap: AirFlowParts ( isTurboCharger() );
		$apf: AirFlowPartsFix( getTurboChargerFix() != null);
	then
		delete($ap);
		fixes.clear();
    	fixes.addAll($apf.getTurboChargerFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($apf.getTurboChargerFix());
end

rule "Spark plug fix"
	when
		$fp: FuelInjectionParts ( isSparkPlug() );
		$fipf: FuelInjectionPartsFix( getSparkPlugFix() != null);
	then
		delete($fp);
		fixes.clear();
    	fixes.addAll($fipf.getSparkPlugFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($fipf.getSparkPlugFix());
end

rule "Dualmassflywheel fix"
	when
		$mp: MechanicalParts( isDualMassFlyWheel() );
		$mpf: MechanicalPartsFix( getDualMassFlyWheelFix() != null);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getDualMassFlyWheelFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getDualMassFlyWheelFix());

end

rule "Tyre fix"
	when
		$mp: MechanicalParts( isTyre() );
		$mpf: MechanicalPartsFix( getTyreFix() != null);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($mpf.getTyreFix());
		RuleReturnTest rr = new RuleReturnTest();
		rr.ruleReturn($mpf.getTyreFix());

end




	


