package rules;

import com.ftn.carDiagnostic.model.fix.ElectricalPartsFix;
import com.ftn.carDiagnostic.model.fix.FluidPartsFix
import com.ftn.carDiagnostic.model.fix.MechanicalPartsFix;
import com.ftn.carDiagnostic.model.fix.FuelInjectionPartsFix;
import com.ftn.carDiagnostic.model.fix.AirFlowPartsFix;


global java.util.List fixes;
global java.util.List appointments;

//DRUGA GRUPA PRAVILA, NA OSNOVU PROBLEMATICNOG DELA SE PRONALAZI POPRAVKA ZA ISTI

//ELECTRICAL PROBLEMS




rule "FAILURE ID-1 -loginFail multiple"
	when
	    $log: Log( getId() == 1 && getMessage() == 'login_fail' , $user: userName );
	    Number(intValue >= 2) from accumulate(
        $log2: Log( this != $log, userName == $user, this meets[10s] $log),count($log2))
	then
		fixes.clear();
		fixes.add("ALERT! : Multiple failed login for short time! Time: " + $log.getExecutionTime() + "| Message: " + $log.getMessage() + "\n USER DEACTIVATED!");
		delete($log);
end 

rule "Headlight fix"
    when
        $ep: ElectricalParts( isHeadlight() == true );
        $epf: ElectricalPartsFix( $headlightFix: headlightFix);
       
    then
    	
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($headlightFix); //Pozivam metodu u kojoj ce rule da vrati Fix korisniku na front 
    	

 end 

rule "Taillight fix"
    when
        $ep: ElectricalParts( isTailLight() == true );
        $epf: ElectricalPartsFix( $taillightFix: taillightFix);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($taillightFix);
   		
end 

rule "ElectricWindows fix"
    when
        $ep: ElectricalParts( isElectricWindows() == true );
        ElectricalPartsFix( $electricWindowsFix : electricWindowsFix);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($electricWindowsFix);
    	
end 

rule "Battery fix"
    when
        $ep: ElectricalParts( isBattery() == true );
        ElectricalPartsFix( $batteryFix: batteryFix);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($batteryFix);
   		
end 

rule "Alternator fix"
    when
        $ep: ElectricalParts( isAlternator() == true );
        ElectricalPartsFix( $alternatorFix: alternatorFix);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($alternatorFix);
   		
end 

rule "Electrical fan"
    when
        $ep: ElectricalParts( isElectricFan() == true );
        $epf: ElectricalPartsFix( $electricFanFix: electricFanFix);
    then
    	delete($ep);
    	fixes.clear();
    	fixes.addAll($electricFanFix);
   		
end 



//FLUID problems

//Verovatno samo kondenzacija, proveriti nivo rashladne tecnosti
rule "Coolant fix"
    when
        $fp: FluidParts( isCoolant() == true );
        $fpf: FluidPartsFix( $coolantFix: coolantFix);
    then
    	delete($fp);
    	fixes.clear();
    	fixes.addAll($coolantFix);
    	
end 

//Proveriti da li ima prijavljen problem sa uljem, jer ovo znaci da motor trosi ulje?
rule "Oil fix"
    when
        $fp: FluidParts( isOil() == true );
        $fpf: FluidPartsFix( $oilFix: oilFix);
    then
    	delete($fp);
    	fixes.clear();
    	fixes.addAll($oilFix);
    	
end 


		
rule "Freon fix"
	when
		$fp: FluidParts( isFreon() == true );
		$fpf: FluidPartsFix ( $freonFix: freonFix );
	then
		delete($fp);
		fixes.clear();
    	fixes.addAll($freonFix);
		
end

//MECHANICAL PART FIX
rule "Brakepad fix"
	when
		$mp: MechanicalParts( isBrakePads() == true);
		$mpf: MechanicalPartsFix( $brakePadsFix: brakePadsFix);
	then
		delete($mp);
		fixes.clear();
    	fixes.addAll($brakePadsFix);
		
end

rule "DPF fix"
	when
		$ap: AirFlowParts( isDieselParticulateFilter() );
		$apf: AirFlowPartsFix( $dpfFix: dpfFix);
	then
		delete($ap);
		fixes.clear();
    	fixes.addAll($dpfFix);
		
end

rule "Shock absorber fix"
	when
		$mp: MechanicalParts( isShockAbsorber() );
		$mpf: MechanicalPartsFix( $shockAbsorberFix: shockAbsorberFix);
	then
		delete($mp);
		fixes.clear();
    	fixes.addAll($shockAbsorberFix);
		
end

rule "Brake Disc fix"
	when
		$mp: MechanicalParts( isBrakeDisc() );
		$mpf: MechanicalPartsFix( $brakeDiscFix: brakeDiscFix);
	then
		delete($mp);
		fixes.clear();
    	fixes.addAll($brakeDiscFix);
		
end


rule "Stabilizer fix"
	when
		$mp: MechanicalParts( isStabilizer() );
		$mpf: MechanicalPartsFix( $stabilizerFix: stabilizerFix);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($stabilizerFix);
		

end

rule "Engine belt fix"
	when
		$mp: MechanicalParts( isEngineBelt() );
		$mpf: MechanicalPartsFix( $engineBeltFix: engineBeltFix);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($engineBeltFix);
		
end

//FUEL INJECTION PARTS FIX
rule "Nozzle fix"
	when
		$fip: FuelInjectionParts( isNozzle() );
		$fipf: FuelInjectionPartsFix( $nozzleFix: nozzleFix);
	then
		delete($fip);
		fixes.clear();
    	fixes.addAll($nozzleFix);
		
end

//AIRFLOW PARTS FIX
rule "Turbo charger fix"
	when
		$ap: AirFlowParts ( isTurboCharger() );
		$apf: AirFlowPartsFix( $turboChargerFix: turboChargerFix);
	then
		delete($ap);
		fixes.clear();
    	fixes.addAll($turboChargerFix);
		
end

rule "Spark plug fix"
	when
		$fp: FuelInjectionParts ( isSparkPlug() );
		$fipf: FuelInjectionPartsFix( $sparkPlugFix: sparkPlugFix);
	then
		delete($fp);
		fixes.clear();
    	fixes.addAll($sparkPlugFix);
		
end

rule "Dualmassflywheel fix"
	when
		$mp: MechanicalParts( isDualMassFlyWheel() );
		$mpf: MechanicalPartsFix( $dualMassFlyWheelFix: dualMassFlyWheelFix);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($dualMassFlyWheelFix);
		

end

rule "Tyre fix"
	when
		$mp: MechanicalParts( isTyre() );
		$mpf: MechanicalPartsFix( $tyreFix: tyreFix);
	then	
		delete($mp);
		fixes.clear();
    	fixes.addAll($tyreFix);

end




	


