package rules;

import com.ftn.carDiagnostic.model.VisualSymptom;
import com.ftn.carDiagnostic.model.ElectricalParts;
import com.ftn.carDiagnostic.model.FluidParts;
import com.ftn.carDiagnostic.model.MechanicalParts;
import com.ftn.carDiagnostic.model.FuelInjectionParts;
import com.ftn.carDiagnostic.model.FeelingSymptom
import com.ftn.carDiagnostic.model.AudioSymptom
//visual symptoms

rule "Headlight not working symptom"
    when
        $vs: VisualSymptom( isHeadlightNotWorking() == true );
    then
    	delete($vs); //izbaci simptom iz baze znanja
    	//pravi novi electrical parts problem gde je samo headlight true 
       	//$vs.setHeadlightNotWorking(false);
       	ElectricalParts ep = new ElectricalParts();
       	ep.setHeadlight(true);
       	insert(ep);
       	System.out.println("Uspeo da setujem da je problem u headlight");
        //update($vs);
end 



rule "Taillight not working symptom"
    when
        $vs: VisualSymptom( isTaillightNotWorking() == true );
    then
   		delete($vs); //izbaci simptom iz baze znanja
   		ElectricalParts ep = new ElectricalParts();
       	ep.setTailLight(true); //pravi novi electrical parts problem gde je samo taillight true 
       	//$vs.setHeadlightNotWorking(false);
       	insert(ep);
       	System.out.println("Uspeo da setujem da je problem u taillight");
        //update($vs);
end 

rule "Electric windows not working"
    when
        $vs: VisualSymptom( isElectricWindowNotWorking() == true );
    then
    	ElectricalParts ep = new ElectricalParts();
       	ep.setElectricWindows(true); //pravi novi electrical parts problem gde je samo taillight true 
    	  //pravi novi electrical parts problem gde je samo taillight true 
       	//$vs.setHeadlightNotWorking(false);
       	insert(ep);
       	System.out.println("Uspeo da setujem da je problem u Electric windows");
        //update($vs);
end 

rule "battery, isEngineStartProblem problem"
    when
        $vs: VisualSymptom( isEngineStartProblem() == true );
    then
    	insert(new ElectricalParts(false, false, false, true));  
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u battery");
        //update($vs);
end 


rule "coolant dash light"
    when
        $vs: VisualSymptom( isCoolantDashLight() == true );
    then
    	insert(new FluidParts(false, true, false, false, false, false, 0));  
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u coolant");
        //update($vs);
end 

rule "oil dash light"
    when
        $vs: VisualSymptom( isOilDashLight() == true );
    then
    	delete($vs); //izbaci simptom iz baze znanja
    	insert(new FluidParts(true, false, false, false, false, false, 0));  
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u oil");
        //update($vs);
end 

rule "steering fluid dash light"
    when
        $vs: VisualSymptom( isSteeringWheelDashLight() == true );
    then
    	insert(new FluidParts(false, false, true, false, false, false, 0));  
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u steering fluid");
        //update($vs);
end 


rule "white smoke on exhaust, engine gasket fail"
    when
        $vs: VisualSymptom( isWhiteSmoke() == true );
    then
    	insert(new MechanicalParts(false, false, false, false, false, true, false));  
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u engine gasket -> mechanic");
        //update($vs);
end 

rule "blue smoke on exhaust"
    when
        $vs: VisualSymptom( isBlueSmoke() == true );
    then
    	insert(new MechanicalParts(false, false, false, false, false, false, true)); 
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u engine oil consumption -> mechanic");
        //update($vs);
end


rule "black smoke on exhaust"
    when
        $vs: VisualSymptom( isBlackSmoke() == true );
    then
    	insert(new FuelInjectionParts(false, false, true, false)); 
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u nozzle");
        //update($vs);
end

rule "Brakepad dash light - Visual Symptom"
	when
		$vs: VisualSymptom( isBrakePadsDashLight() );
	then
		MechanicalParts mp = new MechanicalParts();
		mp.setBrakePads(true);
		insert(mp);
		System.out.println("Mechanical part problem - SET");
end

rule "Air condition not working"
	when
		$vs: VisualSymptom( isAirConditionNotWorking() );
	then
		FluidParts fp = new FluidParts();
		fp.setFreon(true);
		fp.setLevel(0);
		insert(fp);
		System.out.println("Fluid problem - SET");
end

rule "DPF dash light On"
	when
		$vs: VisualSymptom( isDpfDashLight() );
	then
		AirFlowParts ap = new AirFlowParts();
		ap.setDieselParticulateFilter(true);
		insert(ap);
		System.out.println("Airflow part problem - SET");
end



// Feels like symptoms
rule "Vehicle rides uncomforbaly"
	when
		$fs: FeelingSymptom( isRidesUncomfortable() );
	then
		MechanicalParts mp = new MechanicalParts();
		mp.setShockAbsorber(true);
		insert(mp);
		System.out.println("Mechanical part problem - SET");
end

// Audio symptom
rule "Grinding symptom"
	when
		$as: AudioSymptom (isGrinding());
	then
		MechanicalParts mp = new MechanicalParts();
		mp.setBrakeDisc(true);
		insert(mp);
		System.out.println("Brake Disc Problem - SET");
end

rule "Knocking symptom"
	when
		$as: AudioSymptom (isKnocking());
	then
		FuelInjectionParts fip = new FuelInjectionParts();
		fip.setNozzle(true);
		insert(fip);
		System.out.println("Nozzle Problem - SET");
end

rule "Whistling symptom"
	when
		$as: AudioSymptom (isWhistling());
	then
		AirFlowParts ap = new AirFlowParts();
		ap.setTurboCharger(true);
		insert(ap);
		System.out.println("Turbo charger problem - SET");
end

rule "Ticking symptom"
	when
		$as: AudioSymptom (isTicking());
	then
		MechanicalParts mp = new MechanicalParts();
		mp.setStabilizer(true);
		insert(mp);
		System.out.println("Stabilizer Problem - SET");
end



