package rules;

import com.ftn.carDiagnostic.model.VisualSymptoms;
import com.ftn.carDiagnostic.model.ElectricalParts;
import com.ftn.carDiagnostic.model.ElectricalPartsFix;
import java.util.List;


rule "Headlight not working symtom"
    when
        $vs: VisualSymptoms( isHeadlightNotWorking() == true );
    then
    	insert(new ElectricalParts(true, false, false, false, false, false));  //pravi novi electrical parts problem gde je samo headlight true 
       	//$vs.setHeadlightNotWorking(false);
       	System.out.println("Uspeo da setujem da je problem u headlight");
        //update($vs);
end 

rule "Headlight fix"
    when
        $ep: ElectricalParts( isHeadlight() == true );
        $epf: ElectricalPartsFix( getHeadlightFix() != null);
    then
       	System.out.println($epf.getHeadlightFix());
end 

